// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v5.29.3
// source: proto/speechanalysis/speechanalysis.proto

package speechanalysis

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// SpeechAnalysisClient is the client API for SpeechAnalysis service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SpeechAnalysisClient interface {
	StreamSentiment(ctx context.Context, opts ...grpc.CallOption) (SpeechAnalysis_StreamSentimentClient, error)
}

type speechAnalysisClient struct {
	cc grpc.ClientConnInterface
}

func NewSpeechAnalysisClient(cc grpc.ClientConnInterface) SpeechAnalysisClient {
	return &speechAnalysisClient{cc}
}

func (c *speechAnalysisClient) StreamSentiment(ctx context.Context, opts ...grpc.CallOption) (SpeechAnalysis_StreamSentimentClient, error) {
	stream, err := c.cc.NewStream(ctx, &SpeechAnalysis_ServiceDesc.Streams[0], "/speechanalysis.SpeechAnalysis/StreamSentiment", opts...)
	if err != nil {
		return nil, err
	}
	x := &speechAnalysisStreamSentimentClient{stream}
	return x, nil
}

type SpeechAnalysis_StreamSentimentClient interface {
	Send(*AudioChunk) error
	CloseAndRecv() (*SentimentResponse, error)
	grpc.ClientStream
}

type speechAnalysisStreamSentimentClient struct {
	grpc.ClientStream
}

func (x *speechAnalysisStreamSentimentClient) Send(m *AudioChunk) error {
	return x.ClientStream.SendMsg(m)
}

func (x *speechAnalysisStreamSentimentClient) CloseAndRecv() (*SentimentResponse, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(SentimentResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// SpeechAnalysisServer is the server API for SpeechAnalysis service.
// All implementations must embed UnimplementedSpeechAnalysisServer
// for forward compatibility
type SpeechAnalysisServer interface {
	StreamSentiment(SpeechAnalysis_StreamSentimentServer) error
	mustEmbedUnimplementedSpeechAnalysisServer()
}

// UnimplementedSpeechAnalysisServer must be embedded to have forward compatible implementations.
type UnimplementedSpeechAnalysisServer struct {
}

func (UnimplementedSpeechAnalysisServer) StreamSentiment(SpeechAnalysis_StreamSentimentServer) error {
	return status.Errorf(codes.Unimplemented, "method StreamSentiment not implemented")
}
func (UnimplementedSpeechAnalysisServer) mustEmbedUnimplementedSpeechAnalysisServer() {}

// UnsafeSpeechAnalysisServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SpeechAnalysisServer will
// result in compilation errors.
type UnsafeSpeechAnalysisServer interface {
	mustEmbedUnimplementedSpeechAnalysisServer()
}

func RegisterSpeechAnalysisServer(s grpc.ServiceRegistrar, srv SpeechAnalysisServer) {
	s.RegisterService(&SpeechAnalysis_ServiceDesc, srv)
}

func _SpeechAnalysis_StreamSentiment_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(SpeechAnalysisServer).StreamSentiment(&speechAnalysisStreamSentimentServer{stream})
}

type SpeechAnalysis_StreamSentimentServer interface {
	SendAndClose(*SentimentResponse) error
	Recv() (*AudioChunk, error)
	grpc.ServerStream
}

type speechAnalysisStreamSentimentServer struct {
	grpc.ServerStream
}

func (x *speechAnalysisStreamSentimentServer) SendAndClose(m *SentimentResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *speechAnalysisStreamSentimentServer) Recv() (*AudioChunk, error) {
	m := new(AudioChunk)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// SpeechAnalysis_ServiceDesc is the grpc.ServiceDesc for SpeechAnalysis service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SpeechAnalysis_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "speechanalysis.SpeechAnalysis",
	HandlerType: (*SpeechAnalysisServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamSentiment",
			Handler:       _SpeechAnalysis_StreamSentiment_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "proto/speechanalysis/speechanalysis.proto",
}
